[project]
name = "streams"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-flink>=1.20.0",
    "setuptools>=75.8.0",
]
