apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "streaming-operator.workloadNamespace" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "streaming-operator.labels" . | nindent 4 }}
