apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "streaming-operator.fullname" . }}
  labels:
    {{- include "streaming-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [streams.sentry.io]
    resources: [streamingpipelines]
    verbs: [list, watch, patch]
  - apiGroups: [streams.sentry.io]
    resources: [streamingpipelines/status]
    verbs: [patch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "streaming-operator.fullname" . }}
  labels:
    {{- include "streaming-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "streaming-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "streaming-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "streaming-operator.fullname" . }}
  namespace: streaming-pipelines
  labels:
    {{- include "streaming-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, create, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, create, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "streaming-operator.fullname" . }}
  namespace: streaming-pipelines
  labels:
    {{- include "streaming-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "streaming-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "streaming-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
