env:
  topics:
    logical-events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

# These are intended to be runtime-agnostic config
pipeline:
  sources_config:
    myinput:
      bootstrap_servers: localhost:9092
      consumer_group: python-test
      auto_offset_reset: latest

  sinks_config:
    kafkasink:
      bootstrap_servers: localhost:9092

  reduce_config:
    myreduce:
      parallelism: 3

flink:
  parallelism: 2
  sources_config:
    myinput:
      bootstrap_servers: kafka:9093
      consumer_group: python-test
      auto_offset_reset: latest

  sinks_config:
    kafkasink:
      bootstrap_servers: kafka:9093

  reduce_config:
    myreduce:
      parallelism: 3
