env:
  topics:
    events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

pipeline:
  segments:
    [
      {parallelism: 2,
      steps_config: {
        myinput: {
          starts_segment: True,
          common: {
            bootstrap_servers: "kafka:9093",
          flink_overrides: {}
          }
        }
      }
      },

      # If a segment is of length 1, we do not need to specify which steps
      # start the segment
      {
      parallelism: 3,
      steps_config: {
          kafkasink: {
            common: {
              bootstrap_servers: "kafka:9093",
            },
            flink_overrides: {}
        }
      }
      }
    ]
