env:
  topics:
    events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

pipeline:
  segments:
    my_segment:
      parallelism: 2 # This is runtime-agnostic
      steps_config:
        myinput:
          starts_segment: True
          common:
            type: source
            bootstrap_servers: kafka:9093
            consumer_group: python-test
            auto_offset_reset: latest
          flink_overrides:

        parser:
          common:
            type: map

        myfilter:
          common:
            type: filter

        serializer:
          common:
            type: map

    # If a segment is of length 1, we do not need to specify which steps
    # start the segment
    second_segment:
        parallelism: 3
        steps_config:
          kafkasink:
            common:
              type: sink
              bootstrap_servers: kafka:9093
            flink_overrides:
