
# Default configuration
# As of now, the assumption is that local adapters (like Arroyo)
# do not require overrides of this file
env: {}

pipeline:
  adapter_config:
    arroyo:
      write_healthcheck: true
      metrics_sample_rate: 0.01
  segments:
    - steps_config:
        myinput:
          starts_segment: True
          bootstrap_servers: ["127.0.0.1:9092"]
        mysink:
          bootstrap_servers: ["127.0.0.1:9092"]
