env:
  topics:
    events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

pipeline:
  segments:
    my_segment:
      parallelism: 1 # This is runtime-agnostic
      steps_config:
        myinput:
          starts_segment: True
          common:
            type: source
            bootstrap_servers: localhost:9092
            consumer_group: python-test
            auto_offset_reset: latest
          flink_overrides:

        parser:
          common:
            type: map

        myfilter:
          common:
            type: filter

        serializer:
          common:
            type: map

        kafkasink:
          common:
            type: sink
            bootstrap_servers: localhost:9092
          flink_overrides:
