# Default configuration
# As of now, the assumption is that local adapters (like Arroyo)
# do not require overrides of this file
env:
  topics:
    events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

pipeline:
  segments:
    - steps_config:
        myinput:
          starts_segment: True
          bootstrap_servers: "localhost:9092"

        kafkasink:
          bootstrap_servers: "localhost:9092"
