env:
  topics:
    events: events
    transformed-events: transformed-events
    transformed-events-2: transformed-events-2

pipeline:
  segments: [
      steps_config:
      {
        myinput: {
          starts_segment: True,
          common: {
            bootstrap_servers: "localhost:9092",
          },
          flink_overrides: {},
      },

        kafkasink: {
          common: {
            bootstrap_servers: "localhost:9092",
          },
          flink_overrides: {},
        }
      }
  ]
