# Default configuration
# As of now, the assumption is that local adapters (like Arroyo)
# do not require overrides of this file
env: {}

pipeline:
  segments:
    - steps_config:
        myinput:
          starts_segment: True
          bootstrap_servers: "kafka:9093"

        kafkasink2:
          bootstrap_servers: "kafka:9093"

        blah:
          bootstrap_servers: "kafka:9093"

        blah2:
          bootstrap_servers: "kafka:9093"
