# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: streams
  dependencies:
    kafka:
      description: Shared instance of kafka used by sentry services
      remote:
        repo_name: sentry-shared-kafka
        branch: main
        repo_link: https://github.com/getsentry/sentry-shared-kafka.git
  modes:
    default: [kafka]
