apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streams-k8s-operator
rules:
  - apiGroups: ["streams.sentry.io"]
    resources: ["streamingconsumers", "streamingconsumers/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
