# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flink_worker/flink_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flink_worker/flink_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66link_worker/flink_worker.proto\x12\x0c\x66link_worker\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x01\n\x07Message\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x33\n\x07headers\x18\x02 \x03(\x0b\x32\".flink_worker.Message.HeadersEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x15ProcessMessageRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.flink_worker.Message\x12\x12\n\nsegment_id\x18\x02 \x01(\r\"A\n\x16ProcessMessageResponse\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.flink_worker.Message\"\xb5\x01\n\x17ProcessWatermarkRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x43\n\x07headers\x18\x02 \x03(\x0b\x32\x32.flink_worker.ProcessWatermarkRequest.HeadersEntry\x12\x12\n\nsegment_id\x18\x03 \x01(\r\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x10WindowIdentifier\x12\x15\n\rpartition_key\x18\x01 \x01(\t\x12\x19\n\x11window_start_time\x18\x02 \x01(\x03\"\x83\x01\n\x12\x41\x64\x64ToWindowRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.flink_worker.Message\x12\x12\n\nsegment_id\x18\x02 \x01(\r\x12\x31\n\twindow_id\x18\x03 \x01(\x0b\x32\x1e.flink_worker.WindowIdentifier\"]\n\x14TriggerWindowRequest\x12\x31\n\twindow_id\x18\x01 \x01(\x0b\x32\x1e.flink_worker.WindowIdentifier\x12\x12\n\nsegment_id\x18\x02 \x01(\r2\xf6\x02\n\x12\x46linkWorkerService\x12[\n\x0eProcessMessage\x12#.flink_worker.ProcessMessageRequest\x1a$.flink_worker.ProcessMessageResponse\x12_\n\x10ProcessWatermark\x12%.flink_worker.ProcessWatermarkRequest\x1a$.flink_worker.ProcessMessageResponse\x12G\n\x0b\x41\x64\x64ToWindow\x12 .flink_worker.AddToWindowRequest\x1a\x16.google.protobuf.Empty\x12Y\n\rTriggerWindow\x12\".flink_worker.TriggerWindowRequest\x1a$.flink_worker.ProcessMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flink_worker.flink_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE_HEADERSENTRY']._loaded_options = None
  _globals['_MESSAGE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSWATERMARKREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_PROCESSWATERMARKREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=79
  _globals['_MESSAGE']._serialized_end=225
  _globals['_MESSAGE_HEADERSENTRY']._serialized_start=179
  _globals['_MESSAGE_HEADERSENTRY']._serialized_end=225
  _globals['_PROCESSMESSAGEREQUEST']._serialized_start=227
  _globals['_PROCESSMESSAGEREQUEST']._serialized_end=310
  _globals['_PROCESSMESSAGERESPONSE']._serialized_start=312
  _globals['_PROCESSMESSAGERESPONSE']._serialized_end=377
  _globals['_PROCESSWATERMARKREQUEST']._serialized_start=380
  _globals['_PROCESSWATERMARKREQUEST']._serialized_end=561
  _globals['_PROCESSWATERMARKREQUEST_HEADERSENTRY']._serialized_start=179
  _globals['_PROCESSWATERMARKREQUEST_HEADERSENTRY']._serialized_end=225
  _globals['_WINDOWIDENTIFIER']._serialized_start=563
  _globals['_WINDOWIDENTIFIER']._serialized_end=631
  _globals['_ADDTOWINDOWREQUEST']._serialized_start=634
  _globals['_ADDTOWINDOWREQUEST']._serialized_end=765
  _globals['_TRIGGERWINDOWREQUEST']._serialized_start=767
  _globals['_TRIGGERWINDOWREQUEST']._serialized_end=860
  _globals['_FLINKWORKERSERVICE']._serialized_start=863
  _globals['_FLINKWORKERSERVICE']._serialized_end=1237
# @@protoc_insertion_point(module_scope)
