name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - release-sentry-streams/**
  pull_request:

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: sentry_streams/.python-version

      - name: Make environment
        run: |
          make install-dev

      - name: Run streams test
        run: make tests-streams

      - name: Run flink test
        run: make tests-flink
        env:
          FLINK_LIBS: ./flink_libs
