name: Sentry Streams Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Sphinx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        python-version-file: sentry_streams/.python-version
      - name: Build docs
        run: |
          make install-dev
          make docs
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: Publish to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: sentry_streams/docs/build
          force_orphan: true

      - name: Archive Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: sentry_streams/docs/build
