name: Rust

on:
  push:
    branches:
      - main
      - release-sentry-streams/**

  pull_request:

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - run: cargo check --all-features
        working-directory: ./sentry_streams
      - run: cargo fmt --check
        working-directory: ./sentry_streams
      - run: cargo clippy --no-deps --all-features
        working-directory: ./sentry_streams

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Make environment
        run: |
          make install-dev
      - name: Run tests
        working-directory: ./sentry_streams
        run: |
          . .venv/bin/activate
          cargo test
